# SPDX-FileCopyrightText: 2024 Roman Gilg <subdiff@gmail.com>
# SPDX-License-Identifier: MIT
name: Specialized Install Dependencies via Artifact
description: Calls into more generic dep-artifact-generic to install dependencies
inputs:
  secret:
    description: Secret
    required: true
runs:
  using: "composite"
  steps:
    - name: Install Wrapland
      uses: ./.github/actions/dep-artifact-generic
      with:
        repo: winft/wrapland
        dep-name: wrapland
        secret: ${{ inputs.secret }}
    - name: Install Disman
      uses: ./.github/actions/dep-artifact-generic
      with:
        repo: winft/disman
        dep-name: disman
        secret: ${{ inputs.secret }}
